services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: flori-core-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=floricore_dev_pwd
      - POSTGRES_DB=floricore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
